CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(255) NOT NULL UNIQUE,
    account_name VARCHAR(255) NOT NULL,
    balance NUMERIC(19, 2) NOT NULL,
    version BIGINT,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_account_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);

CREATE TABLE transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_reference VARCHAR(255) NOT NULL UNIQUE,
    sender_account_id BIGINT,
    receiver_account_id BIGINT,
    amount NUMERIC(19, 2) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    description VARCHAR(255),
    transaction_date TIMESTAMP NOT NULL,

    CONSTRAINT fk_transaction_sender
        FOREIGN KEY (sender_account_id)
        REFERENCES account(id),

    CONSTRAINT fk_transaction_receiver
        FOREIGN KEY (receiver_account_id)
        REFERENCES account(id)
);

CREATE INDEX idx_transaction_sender
    ON transaction(sender_account_id);

CREATE INDEX idx_transaction_receiver
    ON transaction(receiver_account_id);

CREATE INDEX idx_transaction_date
    ON transaction(transaction_date);